"""create placement tables

Revision ID: 7645fc3c4e53
Revises: 
Create Date: 2026-10-07 15:37:42.331832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7645fc3c4e53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('name', name=op.f('uq_companies_name'))
    )
    op.create_table('placement_outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_outbox'))
    )
    op.create_index('ix_placement_outbox_unpublished', 'placement_outbox', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('label', sa.String(length=9), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='season_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('label', name=op.f('uq_seasons_label'))
    )
    op.create_index('uq_seasons_single_active', 'seasons', ['status'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('drives',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('announced', 'ongoing', 'completed', 'cancelled', name='drive_status'), server_default='announced', nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('results_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_drives_company_id_companies')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_drives_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drives'))
    )
    op.create_index(op.f('ix_drives_company_id'), 'drives', ['company_id'], unique=False)
    op.create_index(op.f('ix_drives_season_id'), 'drives', ['season_id'], unique=False)
    op.create_table('drive_roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.Enum('fte', 'intern', 'intern_ppo', name='job_type'), nullable=False),
    sa.Column('ctc_inr', sa.BigInteger(), nullable=True),
    sa.Column('stipend_inr', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('selected_count', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('ctc_inr >= 0', name=op.f('ck_drive_roles_ctc_non_negative')),
    sa.CheckConstraint('selected_count >= 0', name=op.f('ck_drive_roles_selected_non_negative')),
    sa.CheckConstraint('stipend_inr >= 0', name=op.f('ck_drive_roles_stipend_non_negative')),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], name=op.f('fk_drive_roles_drive_id_drives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drive_roles'))
    )
    op.create_index(op.f('ix_drive_roles_drive_id'), 'drive_roles', ['drive_id'], unique=False)
    op.create_table('drive_rounds',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.Enum('ppt', 'oa', 'gd', 'technical', 'hr', name='round_type'), nullable=False),
    sa.Column('scheduled_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'ongoing', 'completed', name='round_status'), server_default='scheduled', nullable=False),
    sa.Column('shortlisted_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('round_order >= 1', name=op.f('ck_drive_rounds_order_positive')),
    sa.CheckConstraint('shortlisted_count >= 0', name=op.f('ck_drive_rounds_shortlisted_non_negative')),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], name=op.f('fk_drive_rounds_drive_id_drives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drive_rounds')),
    sa.UniqueConstraint('drive_id', 'round_order', name='uq_drive_rounds_drive_order')
    )
    op.create_index(op.f('ix_drive_rounds_scheduled_on'), 'drive_rounds', ['scheduled_on'], unique=False)
    op.create_table('drive_updates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('posted_by', sa.Uuid(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], name=op.f('fk_drive_updates_drive_id_drives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drive_updates'))
    )
    op.create_index(op.f('ix_drive_updates_drive_id'), 'drive_updates', ['drive_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drive_updates_drive_id'), table_name='drive_updates')
    op.drop_table('drive_updates')
    op.drop_index(op.f('ix_drive_rounds_scheduled_on'), table_name='drive_rounds')
    op.drop_table('drive_rounds')
    op.drop_index(op.f('ix_drive_roles_drive_id'), table_name='drive_roles')
    op.drop_table('drive_roles')
    op.drop_index(op.f('ix_drives_season_id'), table_name='drives')
    op.drop_index(op.f('ix_drives_company_id'), table_name='drives')
    op.drop_table('drives')
    op.drop_index('uq_seasons_single_active', table_name='seasons', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('seasons')
    op.drop_index('ix_placement_outbox_unpublished', table_name='placement_outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('placement_outbox')
    op.drop_table('companies')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    for enum_name in ("round_status", "round_type", "job_type", "drive_status", "season_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
