[project]
name = "notifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tatvamjain", email = "tjain_be23@thapar.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
    "redis>=8.1.0",
]

[project.scripts]
notifier = "notifier:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]
